title: 418 I'm a teapod
email: 418@teapod.world
description: >-
  a chill 20 to 30 minutes chatting about life and web tech
baseurl: ""
url: "https://teapod.world"

collections:
  posts:
    permalink: /:slug

plugins:
  - jekyll-feed
